### ISSUE TITLE
Scheduled tasks are not fired

### ISSUE THREAD

**Issue by TheNozomi** [TheNozomi/ConfeBot#155]
Might be related to #119

**Comment by bitomic** [comment]
In production or development?

https://github.com/TheNozomi/ConfeBot/blob/ed2c7a9b075bf7b918a418b84dba51333c884e66/src/lib/structures/Task.ts#L17

If `env.NODE_ENV === 'development'`, then you need to set `{ development: true }` in the Task class. Tasks are disabled by default in dev unless explicitly told by that option, because I would rather not to have `DailyReports.ts` running every time I want to create a new ping command (?)

**Comment by TheNozomi** [comment]
Yeah, I'm aware of that. They're currently not working in the production environment, so it seems unrelated.
